### ISSUE TITLE
[Request] Add option to change shell for nvterm

### ISSUE THREAD

**Issue by FROST8ytes** [NvChad/nvterm#16]
It would be nice if we could set a default shell being used by nvterm in the config file. For example, my default shell is bash but I would like for nvterm to use fish automatically. Is this possible without using chsh to change the whole user's default shell? If not, how would I achieve similar result of using chsh on Windows?

**Comment by zbirenbaum** [comment]
technically this was already possible since the shell was read from `vim.o.shell`, but I exposed it in the config just now under `terminals.shell`

**Comment by FROST8ytes** [comment]
It seems like `:set shell` break nvterm but not NeoVim's default terminal.

https://user-images.githubusercontent.com/24704804/198827316-f49af38d-e2dd-4c1a-9a0a-f8031d49ba2a.mp4

**Comment by zbirenbaum** [comment]
This was because by default, nvterm reads the shell option from the config which is set to vim.o.shell during initialization unless otherwise specified. I removed the shell option from the config defaults, so that if it is undefined vim.o.shell will be respected at runtime, but if the user specifies a shell in their config it may break, although it should just prefer the shell set in the config.

I also added an override flag to nvterm.new for the shell which has the highest priority.
